#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
f0 = 1
f1 = 1
f2 = f0 + f1  #= 2
f3 = f1 + f2  #= 3
f4 = f2 + f3  #= 5
f5 = f3 + f4  #= 8
n =10

def fib(n):
  f0 = 1
  f1 = 1
  termes = []
  while f1 <= 4e6:
      f2 = f0 + f1
      if f2 <= 4e6 and f2 % 2 ==0:
        termes.append(f2)
      f0 = f1
      f1 = f2
  return termes
suite = fib(n)
sum_termes = sum(suite)
print(suite)
print(sum_termes)